name: Docker Build

on:
  # Manually trigger for dev:
  workflow_dispatch: {}
  # Only auto-run for test and prod:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:

  docker-build:
    uses: ./.github/workflows/reusable-docker-build.yaml
    with:
      image_name: "osl-utils"
