---
name: Linting and Formatting
on:
  workflow_call: {}


jobs:

  docker-build:
    uses: ./.github/workflows/reusable-docker-build.yaml
    with:
      image-name: osl-utils

  setup:
    uses: ./.github/workflows/reusable-setup-env.yaml
    with:
      tagname: ${{ github.ref_name }}

  ### All the Linting Now:
  lint-docker:
    runs-on: ubuntu-latest
    needs:
      - setup
      - docker-build
    container:
      image: ${{ needs.docker-build.outputs.container-uri }}:${{ needs.setup.outputs.shortsha }}
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Dockerfiles
        run: |-
          cd /code
          make docker_lint
