---
name: PR - Alert to Merge Requests

on:                                                    # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, review_requested]
    branches:
      - main

jobs:
  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v0.0.8
    if: github.event.pull_request.draft == false
    with:
      tagname: ${{ github.ref_name }}
