name: Publish Code-Quality Image

on:
  # Manually trigger for dev:
  workflow_dispatch: {}
  # Only auto-run for test and prod:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  setup:
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v0.0.4

  docker-build-containers:
    needs:
      - setup
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-docker-build.yaml@v0.0.4
    with:
      image-name: "osl-cq-image"
      context: "cq-image"
