---
name: Publish Code-Quality Image
on:  # yamllint disable-line rule:truthy
  # Manually trigger for dev:
  workflow_dispatch: {}
  # Only auto-run for test and prod:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
jobs:
  setup:
    # yamllint disable-line rule:line-length
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-setup-env.yaml@v0.0.6
  docker-build-containers:
    needs:
      - setup
    # yamllint disable-line rule:line-length
    uses: ASFOpenSARlab/osl-utils/.github/workflows/reusable-docker-build.yaml@v0.0.6
    with:
      image-name: "osl-cq-image"
      context: "cq-image"
      dockerfile: "cq-image/Dockerfile"
