on:
  workflow_call:

env:
  GITHUB_WORKSPACE: '/code'

jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint yaml Files
        run: make yaml_lint

  formatting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Format yaml Files
        run: make yaml_format_check
