on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:test
      env:
        GITHUB_WORKSPACE: /code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint yaml Files
        run: |
          cd /app
          make yaml_lint

  formatting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:test
      env:
        GITHUB_WORKSPACE: /code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Format yaml Files
        run: |
          cd /app
          make yaml_format_check
