on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:test
      volumes: 
        - $GITHUB_WORKSPACE:/code
    steps:
      - name: Make `/code` directory
        run: mkdir /code

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint yaml Files
        run: |
          cd /app
          make yaml_lint

  formatting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:test
      volumes: 
        - $GITHUB_WORKSPACE:/code
    steps:
      - name: Make `/code` directory
        run: mkdir /code

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Format yaml Files
        run: |
          cd /app
          make yaml_format_check
