name: Reusable - Code Quality - Jinja

on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:dev
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint jinja Files
        run: |
          cd /app
          make jinja_lint

  formatting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:dev
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Format jinja Files
        run: |
          cd /app
          make jinja_format_check
