on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint

      - name: Lint yaml Files
        run: |
          find . -name '*.yaml' | while read file; do
              yamllint $file
          done

  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install golang
        run: |
          sudo apt update
          sudo apt-get install --reinstall ca-certificates -y
          sudo apt install golang-go -y
          # Add go to github path
          echo "${HOME}/go/bin" >> $GITHUB_PATH

      - name: Install `yamlfmt`
        run: |
          go install github.com/google/yamlfmt/cmd/yamlfmt@latest

      - name: Format yaml Files
        run: |-
          yamlfmt -dry -quiet . >> yamlfmt-out.txt
          if [ -s yamlfmt-out.txt ]; then
              cat yamlfmt-out.txt
              exit 1
          fi || (echo 'Run `yamlfmt .` to automatically re-format.' && exit 1)
