---
name: Reusable - Code Quality - Dockerfiles
on:  # yamllint disable-line rule:truthy
  workflow_call:
jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:main
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lint Dockerfiles
        run: |-
          cd /app
          make docker_lint
