---
name: Reusable - Code Quality - Python
on:  # yamllint disable-line rule:truthy
  workflow_call:
jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:main
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lint Python
        run: |
          cd /app
          make python_lint_check
  formatting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:msin
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Python Format
        run: |-
          cd /app
          make python_format_check
