---
name: Reusable - Code Quality - YAML
on:  # yamllint disable-line rule:truthy
  workflow_call:
jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:main
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Lint yaml Files
        run: |
          cd /app
          make yaml_lint
  formatting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asfopensarlab/osl-cq-image:main
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Format yaml Files
        run: |-
          cd /app
          make yaml_format_check
