---
    name: Reusable - Mattermost Notify
    
    on:                # yamllint disable-line rule:truthy
      workflow_call:
        inputs:
          message:
            required: true
            type: string
          environment:
            required: true
            type: string
            default: 'dev'
          ICON_URL:
            type: string
        secrets:
          MATTERMOST_WEBHOOK_URL:
            required: true
    
    jobs:
      notify:
        # runs-on: self-hosted
        runs-on: ubuntu-latest
        environment: ${{ inputs.environment }}
        steps:
          - uses: mattermost/action-mattermost-notify@2.0.0
            with:
              # https://developers.mattermost.com/integrate/webhooks/incoming/
              TEXT: ${{ inputs.message }}
              MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
              MATTERMOST_USERNAME: "Github Build Bot"
              MATTERMOST_CHANNEL: "services-private"
              MATTERMOST_ICON_URL: ${{ inputs.ICON_URL || vars.ICON_URL }}
